Changed some CSS for responsiveness and added link to the button
HackYourFuture-CPH/Guide-IT pull request #125
Opened 2021-05-06 12:03 UTC by sandhana14

# Description

Changed some CSS  style for responsiveness of the error page  and added a link to the button

Fixes # (issue)
#23 

# How to test

First, import the error page component in the app.js and add a route for it and then test by running npm run dev

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2021-05-06 21:57 UTC, TITHI1244 approved these changes
To me, the page does not look quite same for very big screens such as over 1800 width. Maybe you can consider using media query :) Good job @sandhana14

2021-05-07 08:37 UTC, sandhana14 commented
> To me, the page does not look quite same for very big screens such as over 1800 width. Maybe you can consider using media query :) Good job @sandhana14

2021-05-07 10:25 UTC, TITHI1244 commented
Seems exactly perfect for small and big both screens :)

2021-05-07 21:00 UTC, rajanibusani reviewed
A very good job @sandhana14 , Your error page is responsive in all desktop screen sizes...👏

2021-05-07 21:01 UTC, rajanibusani approved these changes

2021-05-07 21:35 UTC, rajanibusani reviewed
Hi @ccshah298 Good job Charmi..👏

2021-05-08 14:15 UTC, ccshah298 commented
good job @sandhana14

2021-05-09 10:37 UTC, bytewiz approved these changes

2021-05-09 11:00 UTC, bytewiz requested changes

2021-05-09 11:00 UTC, bytewiz commented on src/client/containers/404Page/404Page.container.js
> +          </Link>
This is not the correct way to write this. think of it as it ends up being HTML and you should not wrap an <a> tag around a <button> tag.

https://stackoverflow.com/questions/6393827/can-i-nest-a-button-element-inside-an-a-using-html5

If you want to navigate to a page using a button this is the correct way to do so :).

https://reactrouter.com/web/api/Hooks/usehistory

2021-05-09 11:36 UTC, bytewiz approved these changes
Perfect 👌

2021-05-09 11:41 UTC, merged