Responsive Quize Result Page
HackYourFuture-CPH/Guide-IT pull request #126
Opened 2021-05-06 16:24 UTC by aijazraja

# Description

responsive  Quiz Result Page. I have changed CSS by adding Media Query in Quiz Result page Container and component Card Result Page(Beth's Component).

Fixes # (issue)

# How to test?
Storybook
You have to change the file name by adding .component to file names of components I  am using here. It is because we merge the Quiz result page component last week with the .component extension in file names. But Anqira PR is still not merged.

# Checklist

- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] This PR is ready to be merged and not breaking any other functionality

2021-05-06 21:04 UTC, TITHI1244 requested changes
Hello Aijaz. I think, we are supposed to add the page path also in the App router, something like this:
```
<Route exact path="/{path_name}">
      <{Your_component_name} />
 </Route>
```
 Then it would be easier to review :)

2021-05-06 21:35 UTC, TITHI1244 requested changes
@aijazraja , can you please change all the pixels into % or em? As I can see, all others are coding like that :)

2021-05-09 10:36 UTC, dpfernandes approved these changes
👍

2021-05-09 10:37 UTC, qamarfj approved these changes

2021-05-09 10:37 UTC, cph-kiwi approved these changes

2021-05-09 10:40 UTC, bytewiz approved these changes

2021-05-09 10:40 UTC, bytewiz commented on src/client/components/CardProfileResult/CardProfileResultComponent.styles.css
>    padding-top: 30px;
Be careful with setting fixed sizes :)

2021-05-09 11:15 UTC, TITHI1244 approved these changes

2021-05-09 11:15 UTC, merged