I have added all the routes for missing pages
HackYourFuture-CPH/Guide-IT pull request #140
Opened 2021-05-11 11:04 UTC by JyothiNandyala

# Description

I have added all the routes for the missing pages in app.js file.

Fixes # (issue)
#118 
# How to test?

give the command like npm run dev then check all the pages with /(link name).

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] This PR is ready to be merged and not breaking any other functionality

2021-05-11 11:59 UTC, dpfernandes requested changes
A few inconsistent names here and few other things: 

Delete these

->  <SignIn exact path="/sign-in" />
->  <SignUp exact path="/sign-up" />
->  <ResetPassword exact path="/reset-password" />

Please hyphens on paths when you use 2 words, example: **quiz-results** instead of **quizresults** 
And remove **page** word from the paths

2021-05-11 17:34 UTC, Enqira commented
Well done Jyothi, but shouldn't you use   <AuthenticatedRoute exact path="/path-name"> instead of  <Route exact path="/path-name"> for the protected routes, because for instance we don't want the client to be able to access career-page, results profile-page, elevator-pitch, etc if they are not authentificated?

2021-05-11 20:31 UTC, valmdz commented on src/client/App.js
> +        <Route exact path="/elevatorpitch">
```suggestion
        <Route exact path="/elevator-pitch">
```

2021-05-11 20:56 UTC, valmdz commented on src/client/App.js
> +        <Route exact path="/error">
The 404 page will be triggered just if the user types the word error on the path, so you probably want to approach this in a different way. I am sure you will be able to find a solution in google :)

2021-05-11 21:12 UTC, JyothiNandyala commented on src/client/App.js
>          <AuthenticatedRoute exact path="/profile">
Yes valentina your right,but still we dont have any authentication for the routers may be we will change those things in the future.

2021-05-11 21:12 UTC, JyothiNandyala commented on src/client/App.js
> +        <Route exact path="/elevatorpitch">
yes i made the change

2021-05-16 10:24 UTC, dpfernandes approved these changes
👍

2021-05-16 10:26 UTC, merged