responsive for registration input
HackYourFuture-CPH/Guide-IT pull request #143
Opened 2021-05-12 12:28 UTC by soujanyapolavarapu

# Description

Responsiveness for Registration input 

Fixes # (#100)

# How to test?

npm run storybook

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2021-05-12 13:55 UTC, dpfernandes requested changes

2021-05-12 13:55 UTC, dpfernandes commented on src/client/containers/RegistrationPage/RegistrationPage.styles.css
> +  width: 25vw;
Please work with percentage (%) like you did with the others css classes

2021-05-14 16:41 UTC, soujanyapolavarapu commented
@dpfernandes Please check and approve this PR i believe, it can be merge now.  :)

2021-05-16 10:30 UTC, dpfernandes approved these changes
👍

2021-05-16 10:36 UTC, rajanibusani approved these changes
It is Responsive in all screens now...

2021-05-16 10:40 UTC, merged