I added Buttons Component task #7
HackYourFuture-CPH/Guide-IT pull request #62
Opened 2021-04-21 09:38 UTC by Poorooshka

# Description

I want to have a button component that can have different labels, colors, text and width so it can be used all over the project along with other components.

Fixes # (issue)

# How to test?

type npm run storybook in your terminal and test the button component on the storybook on your browser.

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2021-04-21 09:56 UTC, cph-kiwi commented
@Poorooshka You need to add an onClick into the .js and stories files - so that the button does something. I think the orange colour is not quite the same as the one in the wireframe. And finally, your button has a border, which the ones in the wireframe do not.

2021-04-21 11:17 UTC, dpfernandes reviewed
The orange is background: #DB643D so that seems correct @cph-kiwi - https://www.figma.com/file/9SJRaxPSuPI3lSl8ULNyJ8/GuideIT-For-Developers?node-id=1%3A1700

2021-04-21 11:38 UTC, soujanyapolavarapu reviewed
I have noticed , inline style `fontFamily` should be like this.

2021-04-21 11:38 UTC, soujanyapolavarapu commented on src/client/components/Buttons/Buttons.js
> +          fontfamily: `${font}`,
In React, Inline style ( fontfamily ) should be fontFamily

2021-04-21 15:46 UTC, soujanyapolavarapu approved these changes

2021-04-22 07:46 UTC, sandhana14 requested changes

2021-04-22 07:46 UTC, sandhana14 commented on src/client/components/Buttons/Buttons.js
> +
I think so You forgot to import(import "./Buttons.styles.css") css file in the js

2021-04-23 11:32 UTC, TITHI1244 requested changes
The code looks nice. Only thing is, you need to find another way to avoid importing classnames. And also remember to delete the fonts' import in css.

2021-04-25 13:29 UTC, ditlevHYF approved these changes

2021-04-25 13:57 UTC, merged