Created a card profile result component
HackYourFuture-CPH/Guide-IT pull request #65
Opened 2021-04-22 14:48 UTC by cph-kiwi

# Description

I created a component to display the results of the quiz, to be able to see different results depending on the answers that a user gives in the quiz. This is so that a user can see the guidance bullet points for their specific result.

Fixes # 16
https://github.com/HackYourFuture-CPH/Guide-IT/issues/16

# How to test?

Open the branch and check the component out in storybook. The component is modelled in two ways, as a personal profile and as a professional profile.

# Checklist

- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] This PR is ready to be merged and not breaking any other functionality

2021-04-22 15:09 UTC, qamarfj approved these changes
looks good

2021-04-22 16:51 UTC, aijazraja reviewed
Hi Beth
The List item part of the professional and personal profile should not a little different in colors? because if you see in the personal profile area it is more white than a professional one.

2021-04-22 19:13 UTC, wwang107 commented
Looking good to me. Nice that you use `flex`, it make life easier.

2021-04-22 19:13 UTC, wwang107 approved these changes
LGTM

2021-04-22 19:15 UTC, wwang107 requested changes
Since someone mention about the background color, could you add a prop that dynamcally change the background color?

2021-04-23 11:37 UTC, cph-kiwi commented
I have had a look at the background colour. It is actually the same in both cases. However an optical illusion happens depending on what the cards are placed on top of that makes them look different to each other. Here is an article about it. Check out the last paragraph and image (square of different shades of grey where the grey colour in the middle of each box is the same colour). https://blog-college.ku.edu/visual-illusion-are-you-teamwhitegold-or-teamblueblack/

2021-04-23 11:51 UTC, TITHI1244 approved these changes
Very nicely done. Working perfectly as intended.

2021-04-23 11:51 UTC, TITHI1244 commented on src/client/components/CardProfileResult/CardProfileResultComponent.styles.css
> +  top: calc(50% - 7px); /* 7px is half the height */
You have nicely designed the bullet point. But do we not need to use images instead from figma? What do you think?

2021-04-24 11:09 UTC, wwang107 approved these changes
Nicely done. Good job

2021-04-24 11:35 UTC, aijazraja approved these changes
Good Job

2021-04-25 07:49 UTC, merged