Quiz Result page is ready for reviews
HackYourFuture-CPH/Guide-IT pull request #76
Opened 2021-04-26 22:04 UTC by aijazraja

# Description

The Quiz Result page is ready for reviews

Fixes #19 

# How to test?

Please use Storybook to test

# Checklist

- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] This PR is ready to be merged and not breaking any other functionality

2021-04-27 10:21 UTC, cph-kiwi requested changes

2021-04-27 10:21 UTC, cph-kiwi commented on src/client/containers/QuizResultPage/QuizResultPage.component.js
> +                  results={resultpersnol}
```suggestion
                  results={resultpersonal}
```

2021-04-27 10:21 UTC, cph-kiwi commented on src/client/containers/QuizResultPage/QuizResultPage.component.js
> +  const resultpersnol = [
```suggestion
  const resultpersonal = [
```

2021-04-27 10:21 UTC, cph-kiwi commented on src/client/containers/QuizResultPage/QuizResultPage.css
> +}
I would like to see this in storybook before commenting on the CSS. However I can't open it in storybook as I'm getting errors around redi-logo.png, in SidebarMenu.js and ResultJobFeatures.js.

2021-05-01 14:46 UTC, qamarfj reviewed
I think you added some extra border.
<img width="972" alt="page" src="https://user-images.githubusercontent.com/64294952/116785984-c57f3380-aa9c-11eb-80c1-00f022eadf05.png">

2021-05-02 09:29 UTC, cph-kiwi requested changes

2021-05-02 09:29 UTC, cph-kiwi commented on src/client/containers/QuizResultPage/QuizResultPage.css
> +.main-div {
I think the name of this file needs changing to QuizResultPage.styles.css, as required in this guidelines page. https://github.com/HackYourFuture-CPH/Guide-IT#coding-guidelines-for-components

2021-05-02 09:29 UTC, cph-kiwi commented on src/client/containers/QuizResultPage/QuizResultPage.component.js
> +            </div>
I think a teaser (https://github.com/HackYourFuture-CPH/Guide-IT/issues/17) was supposed to go in here?

2021-05-02 11:15 UTC, bytewiz approved these changes
Looks good but be careful with large numbers of fixed values in the CSS such as `padding-left: 258px` as they might not be very responsive for the different screen sizes. Just keep it in mind :)

2021-05-02 11:18 UTC, aijazraja commented
> Looks good but be careful with large numbers of fixed values in the CSS such as `padding-left: 258px` as they might not be very responsive for the different screen sizes. Just keep it in mind :)

yea  I will take care of it... can you please approve my PR now :)

2021-05-02 11:31 UTC, qamarfj commented on src/client/containers/QuizResultPage/QuizResultPage.component.js
> +import RegisterTeaser from '../../components/RegisterTeaser/RegisterTeaser';
```suggestion
import RegisterTeaser from '../../components/RegisterTeaser/RegisterTeaser.component';
```

2021-05-02 11:31 UTC, qamarfj commented on src/client/containers/QuizResultPage/QuizResultPage.component.js
> +import CardProfileResultComponent from '../../components/CardProfileResult/CardProfileResultComponent.js';
```suggestion
import CardProfileResultComponent from '../../components/CardProfileResult/CardProfileResult.component.js';
```

2021-05-02 11:31 UTC, qamarfj commented on src/client/containers/QuizResultPage/QuizResultPage.component.js
> +import RobotLogo from '../../components/RobotLogo/RobotLogo';
```suggestion
import RobotLogo from '../../components/RobotLogo/RobotLogo.component';
```

2021-05-02 11:31 UTC, qamarfj commented on src/client/containers/QuizResultPage/QuizResultPage.component.js
> +import PageHeader from '../../components/PageHeaderComponent/PageHeader';
```suggestion
import PageHeader from '../../components/PageHeaderComponent/PageHeader.component';
```

2021-05-02 12:14 UTC, qamarfj approved these changes

2021-05-02 13:00 UTC, merged