I changed the classname from small to small-button
HackYourFuture-CPH/Guide-IT pull request #85
Opened 2021-04-28 08:58 UTC by Poorooshka

# Description

Please provide a short summary explaining what this PR is about.

Fixes # (issue)

# How to test?

Please provide a short summary how your changes can be tested?

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] This PR is ready to be merged and not breaking any other functionality

2021-05-01 12:32 UTC, dpfernandes reviewed
Why is this comment useful? 

//  "small" changed to "small-button" due to conflicts with another CSS file

2021-05-01 17:14 UTC, Enqira requested changes
Good job Nashmil, but could change a couple of things:
On  hover add mouse to pointer and background to a little different color
Also if you could remove the console log, I added a comment on that.

2021-05-02 11:51 UTC, Poorooshka commented on src/client/components/Buttons/Buttons.stories.js
>    onClick: () => {
I did

2021-05-02 14:25 UTC, Enqira approved these changes
Looks good, redy to be merged

2021-05-02 16:04 UTC, Enqira commented
So Nashmil, Daniel pointed that you have a conflict in the Buttons.styles.css, it seems that the file changed while you was making these new changes, and now github does not know what to do, so you have to let it what to do. but don't worry it's easy fix, you can do that clicking on "resolve conflicts". let me know if you need help with that.

2021-05-02 20:32 UTC, Enqira approved these changes
The conflit was solved. some checks have failed but I think those are not related to this PR

2021-05-02 21:47 UTC, dpfernandes approved these changes
👍

2021-05-02 21:47 UTC, merged